import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigation from '../components/navigation'
import Intro from '../components/intro'
import Aboutme from '../components/aboutme'
import Resume from '../components/resume'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Deepak Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Intro/>
      <Aboutme/>
      <Resume/>
        

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
