//LIBS
import Head from 'next/head'
import styles from '../styles/Home.module.css'


//COMPONENTS
import Navigation from '../components/navigation'
import Intro from '../components/intro'
import Aboutme from '../components/aboutme'
import Resume from '../components/resume'
import Project from '../components/projects'




export default function Home() {
  return (
    <div>
      <Head>
        <title>Deepak Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/indian-man.png" />
      </Head>
      <Navigation />
      <Intro sectionID={"top"}/>
      <Aboutme sectionID={"aboutme"}/>
      <Resume sectionID={"resume"}/>
      <Project sectionID={"project"}/>
        

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
